test_add (test_mathfunc.TestMathFunc) ... ok
test_divide (test_mathfunc.TestMathFunc) ... FAIL
test_minus (test_mathfunc.TestMathFunc) ... ok
test_multi (test_mathfunc.TestMathFunc) ... ok

======================================================================
FAIL: test_divide (test_mathfunc.TestMathFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\github\guo.github-io\≈¿≥Ê µ¿˝\unittest π”√\test_mathfunc.py", line 18, in test_divide
    self.assertEqual(2.5,divide(5,2))
AssertionError: 2.5 != 2

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=1)
